<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class AcmeStoreBundleDocumentProductHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $return = $value instanceof \MongoId ? (string) $value : $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['name']) || (! empty($this->class->fieldMappings['name']['nullable']) && array_key_exists('name', $data))) {
            $value = $data['name'];
            if ($value !== null) {
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['name']->setValue($document, $return);
            $hydratedData['name'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['category']) || (! empty($this->class->fieldMappings['category']['nullable']) && array_key_exists('category', $data))) {
            $value = $data['category'];
            if ($value !== null) {
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['category']->setValue($document, $return);
            $hydratedData['category'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['brand']) || (! empty($this->class->fieldMappings['brand']['nullable']) && array_key_exists('brand', $data))) {
            $value = $data['brand'];
            if ($value !== null) {
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['brand']->setValue($document, $return);
            $hydratedData['brand'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['productMaterial']) || (! empty($this->class->fieldMappings['productMaterial']['nullable']) && array_key_exists('productMaterial', $data))) {
            $value = $data['productMaterial'];
            if ($value !== null) {
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['productMaterial']->setValue($document, $return);
            $hydratedData['productMaterial'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['imageUrl']) || (! empty($this->class->fieldMappings['imageUrl']['nullable']) && array_key_exists('imageUrl', $data))) {
            $value = $data['imageUrl'];
            if ($value !== null) {
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['imageUrl']->setValue($document, $return);
            $hydratedData['imageUrl'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['delivery']) || (! empty($this->class->fieldMappings['delivery']['nullable']) && array_key_exists('delivery', $data))) {
            $value = $data['delivery'];
            if ($value !== null) {
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['delivery']->setValue($document, $return);
            $hydratedData['delivery'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['details']) || (! empty($this->class->fieldMappings['details']['nullable']) && array_key_exists('details', $data))) {
            $value = $data['details'];
            if ($value !== null) {
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['details']->setValue($document, $return);
            $hydratedData['details'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['priceFrns1']) || (! empty($this->class->fieldMappings['priceFrns1']['nullable']) && array_key_exists('priceFrns1', $data))) {
            $value = $data['priceFrns1'];
            if ($value !== null) {
                $return = (float) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['priceFrns1']->setValue($document, $return);
            $hydratedData['priceFrns1'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['priceNewFrns1']) || (! empty($this->class->fieldMappings['priceNewFrns1']['nullable']) && array_key_exists('priceNewFrns1', $data))) {
            $value = $data['priceNewFrns1'];
            if ($value !== null) {
                $return = (float) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['priceNewFrns1']->setValue($document, $return);
            $hydratedData['priceNewFrns1'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['priceFrns2']) || (! empty($this->class->fieldMappings['priceFrns2']['nullable']) && array_key_exists('priceFrns2', $data))) {
            $value = $data['priceFrns2'];
            if ($value !== null) {
                $return = (float) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['priceFrns2']->setValue($document, $return);
            $hydratedData['priceFrns2'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['priceNewFrns2']) || (! empty($this->class->fieldMappings['priceNewFrns2']['nullable']) && array_key_exists('priceNewFrns2', $data))) {
            $value = $data['priceNewFrns2'];
            if ($value !== null) {
                $return = (float) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['priceNewFrns2']->setValue($document, $return);
            $hydratedData['priceNewFrns2'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['priceFrns3']) || (! empty($this->class->fieldMappings['priceFrns3']['nullable']) && array_key_exists('priceFrns3', $data))) {
            $value = $data['priceFrns3'];
            if ($value !== null) {
                $return = (float) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['priceFrns3']->setValue($document, $return);
            $hydratedData['priceFrns3'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['priceNewFrns3']) || (! empty($this->class->fieldMappings['priceNewFrns3']['nullable']) && array_key_exists('priceNewFrns3', $data))) {
            $value = $data['priceNewFrns3'];
            if ($value !== null) {
                $return = (float) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['priceNewFrns3']->setValue($document, $return);
            $hydratedData['priceNewFrns3'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['priceFrns4']) || (! empty($this->class->fieldMappings['priceFrns4']['nullable']) && array_key_exists('priceFrns4', $data))) {
            $value = $data['priceFrns4'];
            if ($value !== null) {
                $return = (float) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['priceFrns4']->setValue($document, $return);
            $hydratedData['priceFrns4'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['priceNewFrns4']) || (! empty($this->class->fieldMappings['priceNewFrns4']['nullable']) && array_key_exists('priceNewFrns4', $data))) {
            $value = $data['priceNewFrns4'];
            if ($value !== null) {
                $return = (float) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['priceNewFrns4']->setValue($document, $return);
            $hydratedData['priceNewFrns4'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['minPrice']) || (! empty($this->class->fieldMappings['minPrice']['nullable']) && array_key_exists('minPrice', $data))) {
            $value = $data['minPrice'];
            if ($value !== null) {
                $return = (float) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['minPrice']->setValue($document, $return);
            $hydratedData['minPrice'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['minNewPrice']) || (! empty($this->class->fieldMappings['minNewPrice']['nullable']) && array_key_exists('minNewPrice', $data))) {
            $value = $data['minNewPrice'];
            if ($value !== null) {
                $return = (float) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['minNewPrice']->setValue($document, $return);
            $hydratedData['minNewPrice'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['priceVariation']) || (! empty($this->class->fieldMappings['priceVariation']['nullable']) && array_key_exists('priceVariation', $data))) {
            $value = $data['priceVariation'];
            if ($value !== null) {
                $return = (float) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['priceVariation']->setValue($document, $return);
            $hydratedData['priceVariation'] = $return;
        }
        return $hydratedData;
    }
}